//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dtDBEntities : DbContext
    {
        public dtDBEntities()
            : base("name=dtDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBrand> tblBrand { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblVendor> tblVendor { get; set; }
        public virtual DbSet<tblAttachment> tblAttachments { get; set; }
        public virtual DbSet<tblProject> tblProjects { get; set; }
        public virtual DbSet<tblProjectAudio> tblProjectAudios { get; set; }
        public virtual DbSet<tblProjectBillTo> tblProjectBillToes { get; set; }
        public virtual DbSet<tblProjectConfig> tblProjectConfigs { get; set; }
        public virtual DbSet<tblProjectExteriorMenu> tblProjectExteriorMenus { get; set; }
        public virtual DbSet<tblProjectInstallation> tblProjectInstallations { get; set; }
        public virtual DbSet<tblProjectInteriorMenu> tblProjectInteriorMenus { get; set; }
        public virtual DbSet<tblProjectNetworking> tblProjectNetworkings { get; set; }
        public virtual DbSet<tblProjectNote> tblProjectNotes { get; set; }
        public virtual DbSet<tblProjectPaymentSystem> tblProjectPaymentSystems { get; set; }
        public virtual DbSet<tblProjectPOS> tblProjectPOS { get; set; }
        public virtual DbSet<tblProjectSonicRadio> tblProjectSonicRadios { get; set; }
        public virtual DbSet<tblProjectStakeHolder> tblProjectStakeHolders { get; set; }
        public virtual DbSet<tblProjectStore> tblProjectStores { get; set; }
        public virtual DbSet<tblStore> tblStores { get; set; }
        public virtual DbSet<tblUser1> tblUsers1 { get; set; }
        public virtual DbSet<tblBrandBKP> tblBrandBKPs { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblEnum> tblEnums { get; set; }
        public virtual DbSet<tblEnumTableField> tblEnumTableFields { get; set; }
        public virtual DbSet<tblFranchise> tblFranchises { get; set; }
        public virtual DbSet<tblFunction> tblFunctions { get; set; }
        public virtual DbSet<tblProjectComponent> tblProjectComponents { get; set; }
        public virtual DbSet<tblProjectComponentUpload> tblProjectComponentUploads { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblTechComponent> tblTechComponents { get; set; }
        public virtual DbSet<tblUserBrandRel> tblUserBrandRels { get; set; }
        public virtual DbSet<tblUserFunctionRel> tblUserFunctionRels { get; set; }
        public virtual DbSet<tblDropdownMain> tblDropdownMains { get; set; }
        public virtual DbSet<tblDropdown> tblDropdowns { get; set; }
        public virtual DbSet<tblDocument> tblDocuments { get; set; }
        public virtual DbSet<tblApplicationTrace> tblApplicationTraces { get; set; }
        public virtual DbSet<tblQuoteRequestMain> tblQuoteRequestMains { get; set; }
        public virtual DbSet<tblQuoteRequestTechComp> tblQuoteRequestTechComps { get; set; }
        public virtual DbSet<tblQuoteRequestTechCompField> tblQuoteRequestTechCompFields { get; set; }
        public virtual DbSet<tblTrace> tblTraces { get; set; }
        public virtual DbSet<tblPurchaseOrderTemplate> tblPurchaseOrderTemplates { get; set; }
    
        public virtual int sproc_CreateStoreFromExcel(string tStoreName, string tProjectType, string tStoreNumber, string tAddress, string tCity, string tState, Nullable<int> nDMAID, string tDMA, string tRED, string tCM, string tANE, string tRVP, string tPrincipalPartner, Nullable<System.DateTime> dStatus, Nullable<System.DateTime> dOpenStore, string tProjectStatus, Nullable<int> nCreatedBy, Nullable<int> nBrandId)
        {
            var tStoreNameParameter = tStoreName != null ?
                new ObjectParameter("tStoreName", tStoreName) :
                new ObjectParameter("tStoreName", typeof(string));
    
            var tProjectTypeParameter = tProjectType != null ?
                new ObjectParameter("tProjectType", tProjectType) :
                new ObjectParameter("tProjectType", typeof(string));
    
            var tStoreNumberParameter = tStoreNumber != null ?
                new ObjectParameter("tStoreNumber", tStoreNumber) :
                new ObjectParameter("tStoreNumber", typeof(string));
    
            var tAddressParameter = tAddress != null ?
                new ObjectParameter("tAddress", tAddress) :
                new ObjectParameter("tAddress", typeof(string));
    
            var tCityParameter = tCity != null ?
                new ObjectParameter("tCity", tCity) :
                new ObjectParameter("tCity", typeof(string));
    
            var tStateParameter = tState != null ?
                new ObjectParameter("tState", tState) :
                new ObjectParameter("tState", typeof(string));
    
            var nDMAIDParameter = nDMAID.HasValue ?
                new ObjectParameter("nDMAID", nDMAID) :
                new ObjectParameter("nDMAID", typeof(int));
    
            var tDMAParameter = tDMA != null ?
                new ObjectParameter("tDMA", tDMA) :
                new ObjectParameter("tDMA", typeof(string));
    
            var tREDParameter = tRED != null ?
                new ObjectParameter("tRED", tRED) :
                new ObjectParameter("tRED", typeof(string));
    
            var tCMParameter = tCM != null ?
                new ObjectParameter("tCM", tCM) :
                new ObjectParameter("tCM", typeof(string));
    
            var tANEParameter = tANE != null ?
                new ObjectParameter("tANE", tANE) :
                new ObjectParameter("tANE", typeof(string));
    
            var tRVPParameter = tRVP != null ?
                new ObjectParameter("tRVP", tRVP) :
                new ObjectParameter("tRVP", typeof(string));
    
            var tPrincipalPartnerParameter = tPrincipalPartner != null ?
                new ObjectParameter("tPrincipalPartner", tPrincipalPartner) :
                new ObjectParameter("tPrincipalPartner", typeof(string));
    
            var dStatusParameter = dStatus.HasValue ?
                new ObjectParameter("dStatus", dStatus) :
                new ObjectParameter("dStatus", typeof(System.DateTime));
    
            var dOpenStoreParameter = dOpenStore.HasValue ?
                new ObjectParameter("dOpenStore", dOpenStore) :
                new ObjectParameter("dOpenStore", typeof(System.DateTime));
    
            var tProjectStatusParameter = tProjectStatus != null ?
                new ObjectParameter("tProjectStatus", tProjectStatus) :
                new ObjectParameter("tProjectStatus", typeof(string));
    
            var nCreatedByParameter = nCreatedBy.HasValue ?
                new ObjectParameter("nCreatedBy", nCreatedBy) :
                new ObjectParameter("nCreatedBy", typeof(int));
    
            var nBrandIdParameter = nBrandId.HasValue ?
                new ObjectParameter("nBrandId", nBrandId) :
                new ObjectParameter("nBrandId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sproc_CreateStoreFromExcel", tStoreNameParameter, tProjectTypeParameter, tStoreNumberParameter, tAddressParameter, tCityParameter, tStateParameter, nDMAIDParameter, tDMAParameter, tREDParameter, tCMParameter, tANEParameter, tRVPParameter, tPrincipalPartnerParameter, dStatusParameter, dOpenStoreParameter, tProjectStatusParameter, nCreatedByParameter, nBrandIdParameter);
        }
    
        public virtual ObjectResult<sproc_SearchStore_Result> sproc_SearchStore(string tText)
        {
            var tTextParameter = tText != null ?
                new ObjectParameter("tText", tText) :
                new ObjectParameter("tText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_SearchStore_Result>("sproc_SearchStore", tTextParameter);
        }
    }
}
