//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dtDBEntities : DbContext
    {
        public dtDBEntities()
            : base("name=dtDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBrand> tblBrand { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblVendor> tblVendor { get; set; }
        public virtual DbSet<tblAttachment> tblAttachments { get; set; }
        public virtual DbSet<tblProject> tblProjects { get; set; }
        public virtual DbSet<tblProjectAudio> tblProjectAudios { get; set; }
        public virtual DbSet<tblProjectBillTo> tblProjectBillToes { get; set; }
        public virtual DbSet<tblProjectConfig> tblProjectConfigs { get; set; }
        public virtual DbSet<tblProjectExteriorMenu> tblProjectExteriorMenus { get; set; }
        public virtual DbSet<tblProjectInstallation> tblProjectInstallations { get; set; }
        public virtual DbSet<tblProjectInteriorMenu> tblProjectInteriorMenus { get; set; }
        public virtual DbSet<tblProjectNetworking> tblProjectNetworkings { get; set; }
        public virtual DbSet<tblProjectNote> tblProjectNotes { get; set; }
        public virtual DbSet<tblProjectPaymentSystem> tblProjectPaymentSystems { get; set; }
        public virtual DbSet<tblProjectPOS> tblProjectPOS { get; set; }
        public virtual DbSet<tblProjectSonicRadio> tblProjectSonicRadios { get; set; }
        public virtual DbSet<tblProjectStakeHolder> tblProjectStakeHolders { get; set; }
        public virtual DbSet<tblProjectStore> tblProjectStores { get; set; }
        public virtual DbSet<tblStore> tblStores { get; set; }
        public virtual DbSet<tblUser1> tblUsers1 { get; set; }
        public virtual DbSet<tblBrandBKP> tblBrandBKPs { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblEnum> tblEnums { get; set; }
        public virtual DbSet<tblEnumTableField> tblEnumTableFields { get; set; }
        public virtual DbSet<tblFranchise> tblFranchises { get; set; }
        public virtual DbSet<tblFunction> tblFunctions { get; set; }
        public virtual DbSet<tblProjectComponent> tblProjectComponents { get; set; }
        public virtual DbSet<tblProjectComponentUpload> tblProjectComponentUploads { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblTechComponent> tblTechComponents { get; set; }
        public virtual DbSet<tblUserBrandRel> tblUserBrandRels { get; set; }
        public virtual DbSet<tblUserFunctionRel> tblUserFunctionRels { get; set; }
    }
}
