//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachment
    {
        public int aAttachmentId { get; set; }
        public string tfileName { get; set; }
        public string tFileExt { get; set; }
        public string tfileType { get; set; }
        public string tAttachmentType { get; set; }
        public string tAttachmentComments { get; set; }
        public byte[] tAttachmentBlob { get; set; }
        public string tAttachmentURL { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
    }
}
