//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDropdown: Misc.ModelParent
    {
        public int aDropdownId { get; set; }
        public string tDropdownText { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
        public Nullable<int> nOrder { get; set; }
        public Nullable<int> nFunction { get; set; }
        public Nullable<int> nBrandId { get; set; }
        public Nullable<int> nModuleId { get; set; }
    }
}
