//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnum
    {
        public int aEnumID { get; set; }
        public Nullable<int> nConstraintID { get; set; }
        public Nullable<int> nIndexID { get; set; }
        public string tDisplayName { get; set; }
    }
}
