//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using DeploymentTool.Misc;
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnumTableField : ModelParent
    {
        public int aConstraintID { get; set; }
        public string tTableName { get; set; }
        public string tColumnName { get; set; }
    }
}
