//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblField
    {
        public int aFieldID { get; set; }
        public Nullable<int> nFieldGroupID { get; set; }
        public Nullable<int> nFieldTypeID { get; set; }
        public string tFieldName { get; set; }
        public Nullable<int> nAvailableFlag { get; set; }
        public string tTableName { get; set; }
        public string tColumnName { get; set; }
        public string tPrimaryColumn { get; set; }
        public string tRelColumn { get; set; }
        public Nullable<int> nBrandID { get; set; }
        public string tConstraint { get; set; }
    }
}
