//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFranchise
    {
        public int aFranchiseId { get; set; }
        public string tFranchiseName { get; set; }
        public Nullable<int> nBrandID { get; set; }
        public string tFranchiseDescription { get; set; }
        public string tFranchiseLocation { get; set; }
        public Nullable<System.DateTime> dFranchiseEstablished { get; set; }
        public string tFranchiseContact { get; set; }
        public string tFranchiseOwner { get; set; }
        public string tFranchiseEmail { get; set; }
        public string tFranchisePhone { get; set; }
        public string tFranchiseAddress { get; set; }
        public Nullable<int> nFranchiseEmployeeCount { get; set; }
        public Nullable<int> nFranchiseRevenue { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
        public string tFranchiseAddress2 { get; set; }
        public string tFranchiseCity { get; set; }
        public Nullable<int> nFranchiseState { get; set; }
        public string tFranchiseZip { get; set; }
    }
}
