//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOutgoingEmailAttachment
    {
        public int aOutgoingEmailAttachmentID { get; set; }
        public Nullable<int> nOutgoingEmailID { get; set; }
        public string tFileName { get; set; }
        public string tContentID { get; set; }
        public byte[] ifile { get; set; }
    }
}
