//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectPaymentSystem
    {
        public int aProjectPaymentSystemID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nVendor { get; set; }
        public Nullable<int> nBuyPassID { get; set; }
        public Nullable<int> nServerEPS { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<System.DateTime> dDeliveryDate { get; set; }
        public Nullable<int> nPAYSUnits { get; set; }
        public Nullable<int> n45Enclosures { get; set; }
        public Nullable<int> n90Enclosures { get; set; }
        public Nullable<int> nDTEnclosures { get; set; }
        public Nullable<int> n15SunShields { get; set; }
        public Nullable<int> nUPS { get; set; }
        public Nullable<int> nShelf { get; set; }
        public Nullable<decimal> cCost { get; set; }
        public Nullable<int> nType { get; set; }
    }
}
