//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrderTemplatePart
    {
        public int aPurchaseOrderTemplatePartsID { get; set; }
        public Nullable<int> nPartID { get; set; }
        public Nullable<int> nConfigProjectFieldID { get; set; }
        public Nullable<int> nPurchaseOrderTemplateID { get; set; }
    }
}
