//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPart
    {
        public int aPartID { get; set; }
        public string tPartDesc { get; set; }
        public string tPartNumber { get; set; }
        public Nullable<decimal> cPrice { get; set; }
    }
}
