//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectPOS: Misc.ModelParent
    {
        public int aProjectPOSID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nVendor { get; set; }
        public Nullable<System.DateTime> dDeliveryDate { get; set; }
        public Nullable<System.DateTime> dConfigDate { get; set; }
        public Nullable<System.DateTime> dSupportDate { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<int> nPaperworkStatus { get; set; }
        public Nullable<decimal> cCost { get; set; }
        public Nullable<int> nStoreId { get; set; }
    }
}
