//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrder
    {
        public int aPurchaseOrderID { get; set; }
        public string tPurchaseOrderNumber { get; set; }
        public Nullable<int> nStoreID { get; set; }
        public string tBillingName { get; set; }
        public string tBillingPhone { get; set; }
        public string tBillingEmail { get; set; }
        public string tBillingAddress { get; set; }
        public string tShippingName { get; set; }
        public string tShippingPhone { get; set; }
        public string tShippingEmail { get; set; }
        public string tShippingAddress { get; set; }
        public string tNotes { get; set; }
        public Nullable<System.DateTime> dDeliver { get; set; }
        public Nullable<decimal> cTotal { get; set; }
        public Nullable<int> nOutgoingEmailID { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
        public Nullable<int> nTemplateId { get; set; }
        public string tPDFData { get; set; }
        public string tSentHtml { get; set; }
    }
}
