//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectComponent
    {
        public int aProjectComponentId { get; set; }
        public Nullable<int> nProjectId { get; set; }
        public Nullable<int> nTechComponentId { get; set; }
        public string nVendorId { get; set; }
        public Nullable<int> tStatus { get; set; }
        public string dStartDate { get; set; }
        public Nullable<System.DateTime> dEndDate { get; set; }
        public Nullable<System.DateTime> dEndExpectedDate { get; set; }
        public Nullable<System.DateTime> tSignOffStatus { get; set; }
        public string tComments { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
    }
}
