//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectsRolloutStoreRel: Misc.IModelParent
    {
        public int aProjectsRolloutStoreRelID { get; set; }
        public Nullable<int> nProjectsRolloutID { get; set; }
        public Nullable<int> nStoreID { get; set; }
        public Nullable<int> nLinkedStatus { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nLinkedBy { get; set; }
        public Nullable<System.DateTime> dtLinkedOn { get; set; }
    }
}
