//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectExteriorMenu: Misc.IModelParent
    {
        public int aProjectExteriorMenuID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nVendor { get; set; }
        public Nullable<int> nStalls { get; set; }
        public Nullable<int> nPatio { get; set; }
        public Nullable<int> nFlat { get; set; }
        public Nullable<int> nDTPops { get; set; }
        public Nullable<int> nDTMenu { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<System.DateTime> dDeliveryDate { get; set; }
        public Nullable<decimal> cFabConCost { get; set; }
        public Nullable<decimal> cIDTechCost { get; set; }
        public Nullable<decimal> cTotalCost { get; set; }
        public Nullable<int> nStoreId { get; set; }
        public Nullable<int> nMyActiveStatus { get; set; }
        public Nullable<System.DateTime> dDateFor_nStatus { get; set; }
    }
}
