//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectSonicRadio
    {
        public int aProjectSonicRadioID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nVendor { get; set; }
        public Nullable<int> nOutdoorSpeakers { get; set; }
        public Nullable<int> nColors { get; set; }
        public Nullable<int> nIndoorSpeakers { get; set; }
        public Nullable<int> nZones { get; set; }
        public Nullable<int> nServerRacks { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<System.DateTime> dDeliveryDate { get; set; }
        public Nullable<decimal> cCost { get; set; }
        public Nullable<int> ProjectActiveStatus { get; set; }
    }
}
