//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectNetworking
    {
        public int aProjectNetworkingID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nVendor { get; set; }
        public Nullable<int> nPrimaryStatus { get; set; }
        public Nullable<System.DateTime> dPrimaryDate { get; set; }
        public Nullable<int> nPrimaryType { get; set; }
        public Nullable<int> nBackupStatus { get; set; }
        public Nullable<System.DateTime> dBackupDate { get; set; }
        public Nullable<int> nBackupType { get; set; }
        public Nullable<int> nTempStatus { get; set; }
        public Nullable<System.DateTime> dTempDate { get; set; }
        public Nullable<int> nTempType { get; set; }
    }
}
