//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectsRolloutTechRel: Misc.IModelParent
    {
        public int aProjectsRolloutTechRelID { get; set; }
        public Nullable<int> nProjectsRolloutID { get; set; }
        public Nullable<int> nTechComponentID { get; set; }
        public Nullable<int> nVendorID { get; set; }
        public Nullable<int> nInstallationID { get; set; }
    }
}
