//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectStakeHolder
    {
        public int aProjectStakeHolderID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nFranchisee { get; set; }
        public string tRVP { get; set; }
        public string tFBC { get; set; }
        public string tRED { get; set; }
        public string tCM { get; set; }
        public string tAandE { get; set; }
        public string tPrincipalPartner { get; set; }
        public string tCD { get; set; }
        public string tITPM { get; set; }
    }
}
