//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectsRollout: Misc.IModelParent
    {
        public int aProjectsRolloutID { get; set; }
        public string tProjectsRolloutName { get; set; }
        public string tProjectsRolloutDescription { get; set; }
        public Nullable<int> nBrandID { get; set; }
        public Nullable<int> nNumberOfStore { get; set; }
        public Nullable<int> nMyActiveStatus { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<System.DateTime> dtStartDate { get; set; }
        public Nullable<System.DateTime> dtEndDate { get; set; }
        public string tEstimateIstallTImePerStore { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
        public Nullable<System.DateTime> dDateFor_nStatus { get; set; }
    }
}
