//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectBillTo
    {
        public int aProjectBillToID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public string tCompany { get; set; }
        public string tBillToAddressLine1 { get; set; }
        public string tBillToAddressLine2 { get; set; }
        public string tBillToState { get; set; }
        public string tBillToZipCode { get; set; }
        public string tBillToEmail { get; set; }
    }
}
