//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectAudio: Misc.IModelParent
    {
        public int aProjectAudioID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nVendor { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<int> nConfiguration { get; set; }
        public Nullable<System.DateTime> dDeliveryDate { get; set; }
        public Nullable<int> nLoopStatus { get; set; }
        public Nullable<int> nLoopType { get; set; }
        public Nullable<System.DateTime> dLoopDeliveryDate { get; set; }
        public Nullable<decimal> cCost { get; set; }
        public Nullable<int> nStoreId { get; set; }
        public Nullable<int> nMyActiveStatus { get; set; }
        public Nullable<System.DateTime> dDateFor_nStatus { get; set; }
        public Nullable<System.DateTime> dDateFor_nLoopStatus { get; set; }
    }
}
