//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectInstallation: Misc.IModelParent
    {
        public int aProjectInstallationID { get; set; }
        public Nullable<int> nProjectID { get; set; }
        public Nullable<int> nVendor { get; set; }
        public string tLeadTech { get; set; }
        public Nullable<System.DateTime> dInstallDate { get; set; }
        public Nullable<System.DateTime> dInstallEnd { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<int> nSignoffs { get; set; }
        public Nullable<int> nTestTransactions { get; set; }
        public Nullable<int> nProjectStatus { get; set; }
        public Nullable<decimal> cCost { get; set; }
        public Nullable<int> nStoreId { get; set; }
        public Nullable<int> nMyActiveStatus { get; set; }
        public Nullable<System.DateTime> dDateFor_nStatus { get; set; }
        public Nullable<System.DateTime> dDateFor_nProjectStatus { get; set; }
        public Nullable<System.DateTime> dRevisitDate { get; set; }
        public Nullable<int> nRevisitDateChanged { get; set; }
        public Nullable<System.DateTime> dInstallTime { get; set; }
        public string tInstallTechNumber { get; set; }
        public string tManagerName { get; set; }
        public string tManagerNumber { get; set; }
        public Nullable<int> nManagerCheckout { get; set; }
        public Nullable<int> nPhotoDeliverables { get; set; }
        public string tInstallNotes { get; set; }
    }
}
