//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public int aProjectID { get; set; }
        public string tProjectName { get; set; }
        public Nullable<int> nStoreID { get; set; }
        public Nullable<System.DateTime> dGoLiveDate { get; set; }
        public Nullable<int> nProjectType { get; set; }
        public Nullable<int> nProjectStatus { get; set; }
        public Nullable<int> nDMAID { get; set; }
        public string tDMA { get; set; }
        public Nullable<int> nBrandID { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
        public Nullable<int> ProjectActiveStatus { get; set; }
    }
}
