//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int aReportID { get; set; }
        public string tName { get; set; }
        public Nullable<int> nReportType { get; set; }
        public string tBrandID { get; set; }
        public string tQuery { get; set; }
        public Nullable<bool> bSproc { get; set; }
        public Nullable<int> nChartType { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
        public Nullable<int> nReportFolderID { get; set; }
    }
}
