//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportColumn
    {
        public int aReportColumns { get; set; }
        public Nullable<int> nReportID { get; set; }
        public string tTitles { get; set; }
        public string tHeaders { get; set; }
        public string tSelectColumns { get; set; }
    }
}
