//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSortColumn
    {
        public int aSortColumnsID { get; set; }
        public Nullable<int> nRelatedID { get; set; }
        public Nullable<int> nRelatedType { get; set; }
        public Nullable<int> nFieldID { get; set; }
        public Nullable<int> nOrder { get; set; }
    }
}
