//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrace
    {
        public int aTraceID { get; set; }
        public string StoreName { get; set; }
        public string ProjectType { get; set; }
        public string StoreNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> DMAID { get; set; }
        public string DMA { get; set; }
        public string RED { get; set; }
        public string CM { get; set; }
        public string ANE { get; set; }
        public string RVP { get; set; }
        public string PrincipalPartner { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public string ProjectStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> nNumberOfTabletsPerStore { get; set; }
        public string tEquipmentVendor { get; set; }
        public Nullable<System.DateTime> dDeliveryDate { get; set; }
        public Nullable<System.DateTime> dRevisitDate { get; set; }
        public Nullable<System.DateTime> dInstallDate { get; set; }
        public string tInstallationVendor { get; set; }
        public string tInstallStatus { get; set; }
        public Nullable<System.DateTime> dShipDate { get; set; }
    }
}
