//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser1
    {
        public int aUserID { get; set; }
        public string tName { get; set; }
        public string tUserName { get; set; }
        public string tPassword { get; set; }
        public string tEmail { get; set; }
        public Nullable<int> nDepartment { get; set; }
        public Nullable<int> nRole { get; set; }
        public string tEmpID { get; set; }
        public string tMobile { get; set; }
        public Nullable<System.DateTime> dLastLoggedInTime { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdateBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
    }
}
