//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public int aVendorId { get; set; }
        public string tVendorName { get; set; }
        public Nullable<int> nTechComponentID { get; set; }
        public string tVendorDescription { get; set; }
        public string tVendorEmail { get; set; }
        public string tVendorAddress { get; set; }
        public string tVendorPhone { get; set; }
        public string tVendorContactPerson { get; set; }
        public string tVendorWebsite { get; set; }
        public string tVendorCountry { get; set; }
        public Nullable<System.DateTime> tVendorEstablished { get; set; }
        public string tVendorCategory { get; set; }
        public string tVendorContact { get; set; }
        public Nullable<int> nCreatedBy { get; set; }
        public Nullable<int> nUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<bool> bDeleted { get; set; }
        public Nullable<int> nBrand { get; set; }
        public Nullable<int> nType { get; set; }
        public Nullable<int> nStatus { get; set; }
        public Nullable<int> nInstallation { get; set; }
        public Nullable<int> nEquipment { get; set; }
    }
}
